.TH metis 1 2010-10 "linux" "heatherly custom tools manual"

.SH NAME
.B metis
\- light, aesthetic, and useful personal task visualizer

.SH PATRON
.B metis-okeanides
(ocean-born) goddess of deep thought and wise counsel

.SH IMAGERY (see HERITAGE in man section 7 for more)
singularly graceful, stately, and regal with supreme gravitas

.SH SUMMARY
.B metis
is a aesthetic, keyboard-centric personal task visualizer with simple ascii
capture, consistent categorization, clean hierarchy for grouping, and meaningful
fields for sorting, searching and filtering.

.SH DOCUMENTATION FILES (see also)
 metis (1)    ***   end-user command line, arguments, and options
 metis (5)          data standards, streams, files, and configuration
 metis (6)          interactive system usage and navigation
 metis (7)          decision rationale, objectives, and overview

.SH TABLE OF CONTENTS
 synopsis           initiate the program from the command line
 formats            arguments to change the application display format
 filters            arguments to limit tasks based on categories
 search             arguments to limit tasks based on content
 urgents            arguments to control debugging focus and volume

.SH SYNOPSIS
.B metis [FORMATS] [FILTERS] [SEARCH]
   which is the primary production version

.B metis_debug [URGENTS] [FORMATS] [FILTERS] [SEARCH]
   which is full production, but with debugging and tracing added

.SH FORMATS

.B metis
has six primary formats depending on your needs

.B -c, --col
.RS 8
a columnar format with twelve (12) slots vertically arranged and is formatted
to fit on a screen 800px high.  this view can manually scroll though up to
99 total tasks if available.
.RE

.B -l, --long
.RS 8
a columnar format with sixteen (16) slots vertically arranged and is formatted
to fit on a screen 1200px high.  this view can manually scroll thought up to
99 total tasks if available.
.RE

.B -t, --tic
.RS 8
a horizontal format with ten (10) slots, but typically only four show at a time
on a 1200px wide screen. this view will automaticall scroll thought tasks
from left or right but will always be populated with ten tasks even if blank.
.RE

.B -b, --base
.RS 8
a horizontal format has ten (10) slots, but typically only four show at a time
on a 1200px wide screen. this view can manually scroll thought tasks from left or right
but will always be populated with ten tasks even if blank.
.RE

.B -w, --wide
.RS 8
a full screen format has forty-eight (48) slots in four columns of twelve which
it perfectly suited for a 1280x800 wide screen.  this view can not contain
any more than the 48 shown.
.RE

.B -x, --extra
.RS 8
a full screen format has sixty-four (64) slots in four columns of sixteen which
it perfectly suited for a 1280x1024 wide screen.  this view can not contain
any more than the 64 shown.
.RE

.SH FILTERS

.B metis
will always take the list of tasks from the ~/g_hlosdo/master.tasks file and
filter it according to one of the following options.  each of these options
is followed by a single filtering character and must not be separated by
an inteviening space.

.B -u<c>
.RS 8
filters only tasks with an urgency value of <c>.  <c> is one of the first
letters of today, days, weeks, months, quarters, years, or backlog.
.RE

.B -i<c>
.RS 8
filters only tasks with an importance value of <c>.  <c> is one of the first
letters of absolutely, need, want, like, idea, or stuff
.RE

.B -e<n>
.RS 8
filters only tasks with an estimate category of <n>.  <n> is sequentially 1=10m,
2=30m, 3=60m, 4=120m, 5=240m, 6=480m, 0=unknown.
.RE

.B -f<c>
.RS 8
filters only tasks with an flag value of <c>.  <c> is one of -=active,
X=cancelled, #=complete, O=wip
.RE

.SH SEARCH

if text is provided, 
.B metis
will search the two heirarchy layers for matching values and only show those.






.SH FILES

.I ~/g_hlosdo/master.tasks
.RS 3
this file contains the standard, consolidated tasks list of which metis will
read the first 64 that meet the filtering criteria
.RE

.SH AUTHOR
the_heatherlys

.SH COLOPHON
this page is part of a documentation package meant to make our use of the
heatherly tools easier and faster

