." heatherly hand crafted (like a dope)
."
." sections, break up the document into pieces
."   .SH <str>   begin a new section
."   .SS <str>   begin a new sub-section
."
." paragraphs, if not special formatting is used, these are unnecessary
."   .PP         before a set of contiguous lines will run them together into
."               a single paragraph -- helps if macros separate by accident
."   .RS <n>     start a paragraph indented by <n> characters (i use 3 mostly)
."   .RE         end that relative paragraph
."   .IP <str>   uses <str> as an outdent and the next line is indented
."   .TP         tag paragraph which has a more controllable outdent than .IP
."   .HP         start hanging paragraph where all following lines are indented
."
."
."
."
."
.TH metis 1 2010-Dec "linux" "heatherly custom tools manual"

.SH NAME
metis \- light, fast, clean, and powerful task management visualizer

.SH SYNOPSIS
.nf
.B metis [FILTERS] [FORMAT] [SEARCH]
.nf

.SH DESCRIPTION
metis is a task/todo visualizer that establishes a categorization framework
which allows us to quickly capture tasks, group them into a two layer
hierarchy, and identify several meaningful and standard sorting fields.

we are not indending a traditional, all-in-one application, so....
   - no specialized database, we will use ascii text files
   - no captive editor, we'll just use vi
   - no complicated fields that require extensive error checking
   - no calendaring/scheduling, specific application and separate
   - no repeat, also a scheduling thing or a daily cycle
   - no mice and menus (what idiot thinks these are productive) :<
   - no full screen interference and fancy logo crap
   - no tool tips and help screens

we are focused specifically on our own use and don't need all the hand
coddling -- focusing on technically strong power users that just need
structure and sweet visualization without all the contraints.  we also
need a system that we can tune/adjust without jumping through hoops.

our expectation is that this will be a read-only, sexy, opengl visualizer
weighing in at less than 1,000 source lines of code.  it will display tasks
in the same format everytime and use color coding to make filtering and
review as quick and efficient as possible.  it will also specialize in
formats that can share the screen with programming windows.

metis will integrate the following rational limits/standards...
   - read its tasks from ~/g_hlosdo/master.tasks
   - provide defaults for incorrect/misunderstood task information
   - show up to 99 tasks depending on the view (not infinite)

.SH FILTERS

.B metis
will always take the list of tasks from the ~/g_hlosdo/master.tasks file and
filter it according to one of the following options.  each of these options
is followed by a single filtering character and must not be separated by
an inteviening space.

.B -u<c>
.RS 8
filters only tasks with an urgency value of <c>.  <c> is one of the first
letters of today, days, weeks, months, quarters, years, or backlog.
.RE

.B -i<c>
.RS 8
filters only tasks with an importance value of <c>.  <c> is one of the first
letters of absolutely, need, want, like, idea, or stuff
.RE

.B -e<n>
.RS 8
filters only tasks with an estimate category of <n>.  <n> is sequentially 1=10m,
2=30m, 3=60m, 4=120m, 5=240m, 6=480m, 0=unknown.
.RE

.B -f<c>
.RS 8
filters only tasks with an flag value of <c>.  <c> is one of -=active,
X=cancelled, #=complete, O=wip
.RE

.SH FORMATS

.B metis
has six primary formats depending on your needs

.B -c, --col
.RS 8
a columnar format with twelve (12) slots vertically arranged and is formatted
to fit on a screen 800px high.  this view can manually scroll though up to
99 total tasks if available.
.RE

.B -l, --long
.RS 8
a columnar format with sixteen (16) slots vertically arranged and is formatted
to fit on a screen 1200px high.  this view can manually scroll thought up to
99 total tasks if available.
.RE

.B -t, --tic
.RS 8
a horizontal format with ten (10) slots, but typically only four show at a time
on a 1200px wide screen. this view will automaticall scroll thought tasks
from left or right but will always be populated with ten tasks even if blank.
.RE

.B -b, --base
.RS 8
a horizontal format has ten (10) slots, but typically only four show at a time
on a 1200px wide screen. this view can manually scroll thought tasks from left or right
but will always be populated with ten tasks even if blank.
.RE

.B -w, --wide
.RS 8
a full screen format has forty-eight (48) slots in four columns of twelve which
it perfectly suited for a 1280x800 wide screen.  this view can not contain
any more than the 48 shown.
.RE

.B -x, --extra
.RS 8
a full screen format has sixty-four (64) slots in four columns of sixteen which
it perfectly suited for a 1280x1024 wide screen.  this view can not contain
any more than the 64 shown.
.RE

.SH SEARCH

if text is provided, 
.B metis
will search the two heirarchy layers for matching values and only show those.


.SH RUN-TIME OPTIONS
.sp
while running, 
.B metis
responds to a number of keys
.IP _
go to the first task
.IP G
go to the last task
.IP j,l,>
scroll down/right/forward one task depending on view
.IP k,h,<
scroll up/left/backward one task depending on view
.IP Q 
exit the application
.IP R 
refresh by rereading input file
.IP T 
switch to ticker format
.IP B 
switch to baseline format
.IP C 
switch to columnar format
.IP L 
switch to long columnar format
.IP 1 
switch to columnar format on left
.IP 2 
switch to long columnar format on left
.IP W 
switch to wideview format
.IP X 
switch to extra format
.IP H 
toggle card grouping headers on and off
.IP F 
toggle filtering (given on command line) on and off
.IP p 
print the tasks to stdout
.IP , 
start automatic scrolling if in ticker mode
.IP . 
stop automatic scrolling if in ticker mode
.IP u 
change the urgency filter, or space for clear
.IP i 
change the importance filter, or space for clear
.IP e 
change the estimate filter, or space for clear
.IP f 
change the flag filter, or space for clear
.IP s,/
change the search text terminated with <cr>, null to clear
.IP a 
reset to no filtering
.IP ? 
scroll to show the criteria card

.SH FILES

.I ~/g_hlosdo/master.tasks
.RS 3
this file contains the standard, consolidated tasks list of which metis will
read the first 64 that meet the filtering criteria
.RE

.SH BUGS

the directories are hard coded for the users dotsuu and greatbigc right now

.SH RESOURCES
will only work on an xwindows and opengl system and is probably not worth
using without hardware acceleration

.SH AUTHOR
the_heatherlys

.SH HERITAGE
metis is the greek goddess of cunning and wise counsel.  she was the
first love of zeus and guided him through the titan/olympian war.  metis
was killed by zeus because he feared a prophecy that their children would
displace him (as he had done to his father).  their only child was the
goddess athena.

.SH COLOPHON
this page is part of a documentation package meant to make our use of the
heatherly tools easier and faster

